services:
  db:
    image: postgres:14.1-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: pablo
      POSTGRES_PASSWORD: example
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
volumes:
  db:
    driver: local
