name: Run Tests

# Ejecutar la acción en los eventos pull request y push en la rama main
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Usa una máquina virtual de Ubuntu

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Instalar dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run unit tests
        run: |
          ls -la
          pytest -m "unit"
